import { CircleDollarSign, Wallet, BarChart3, ArrowUpLeft, ArrowDownLeft, Receipt } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { WorkspaceShell } from "./Workspaces";

export default function AdminFinancePage() {
  const overview = trpc.admin.overview.useQuery();
  const resources = trpc.admin.resources.useQuery();
  const cards = [["Income", `${overview.data?.revenue ?? 0} SAR`, CircleDollarSign], ["Expenses", `${overview.data?.expenses ?? 0} SAR`, Wallet], ["Net profit", `${overview.data?.profit ?? 0} SAR`, BarChart3], ["Receivables", `${overview.data?.outstandingInvoices ?? 0} SAR`, Receipt]] as const;
  return <WorkspaceShell mode="admin"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="text-xs uppercase tracking-[.18em] text-[#d8b36a]">Finance</div><h1 className="mt-3 font-display text-4xl font-semibold">Profit & loss</h1><p className="mt-3 text-[#95897b]">Reconciled from paid payments, invoices, and expense records. Empty values remain zero until records exist.</p></div><div className="flex gap-2"><Link href="/admin/income" className="btn-ghost text-xs"><ArrowUpLeft size={14} />Income</Link><Link href="/admin/expenses" className="btn-ghost text-xs"><ArrowDownLeft size={14} />Expenses</Link></div></div><div className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon]) => <div className="glass rounded-2xl p-5" key={label}><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#d8b36a]/10 text-[#d8b36a]"><Icon size={18} /></span><div className="mt-7 font-display text-2xl text-[#f7f2e9]">{value}</div><div className="mt-1 text-sm text-[#a99d90]">{label}</div></div>)}</div><div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="glass overflow-hidden rounded-3xl"><div className="border-b border-white/8 px-6 py-5"><h2 className="font-semibold">Recent income</h2><p className="mt-1 text-xs text-[#8f8375]">Payment records marked PAID.</p></div><div className="divide-y divide-white/8">{resources.data?.payments.filter(item => item.status === "PAID").slice(0, 8).map(item => <div className="flex items-center justify-between px-6 py-4" key={item.id}><div><div className="text-sm">{item.transactionId || `Payment #${item.id}`}</div><div className="mt-1 text-xs text-[#8f8375]">{item.method}</div></div><div className="text-sm text-emerald-200">+{item.amount} SAR</div></div>)}{!resources.data?.payments.filter(item => item.status === "PAID").length && <div className="p-12 text-center text-sm text-[#8f8375]">No data available yet. Paid payment records will appear here.</div>}</div></section><section className="glass overflow-hidden rounded-3xl"><div className="border-b border-white/8 px-6 py-5"><h2 className="font-semibold">Recent expenses</h2><p className="mt-1 text-xs text-[#8f8375]">Every expense row is sourced from the finance table.</p></div><div className="divide-y divide-white/8">{resources.data?.expenses.slice(0, 8).map(item => <div className="flex items-center justify-between px-6 py-4" key={item.id}><div><div className="text-sm">{item.title}</div><div className="mt-1 text-xs text-[#8f8375]">{item.category}</div></div><div className="text-sm text-rose-200">-{item.amount} SAR</div></div>)}{!resources.data?.expenses.length && <div className="p-12 text-center text-sm text-[#8f8375]">No data available yet. Add an expense to begin tracking.</div>}</div></section></div></WorkspaceShell>;
}
