import { Link } from "wouter";
import { ArrowLeft, ArrowUpLeft, Check, ChevronDown, CircleDot, Cloud, Code2, Cpu, Globe2, Layers3, Menu, PenTool, Quote, ShieldCheck, Smartphone, Sparkles, Workflow, Zap } from "lucide-react";
import { useState } from "react";
import { PublicShell, SectionHeading } from "@/components/AthrShell";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";

const iconMap: Record<string, typeof Globe2> = { Globe2, Sparkles, PenTool, Workflow, Smartphone, Cloud, Code2, Cpu };
const process = [["01", "الاكتشاف", "Discovery"], ["02", "الاستراتيجية", "Strategy"], ["03", "التصميم", "Design"], ["04", "التطوير", "Development"], ["05", "الإطلاق", "Launch"]] as const;

export default function Home() {
  const { isArabic } = useLanguage();
  const { data, isLoading, error } = trpc.content.all.useQuery();
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const t = (ar: string, en: string) => isArabic ? ar : en;
  const stats = data?.settings ?? {};
  return <PublicShell>
    <section className="relative min-h-[760px] overflow-hidden bg-grid pt-32 sm:pt-40">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_76%_25%,rgba(216,179,106,.16),transparent_26%),radial-gradient(circle_at_20%_20%,rgba(128,94,33,.10),transparent_20%)]" />
      <div className="pointer-events-none absolute end-[13%] top-32 h-96 w-96 rounded-full border border-[#d8b36a]/20 blur-[1px]" /><div className="pointer-events-none absolute end-[17%] top-48 h-72 w-72 rounded-full border border-[#d8b36a]/15" /><div className="pointer-events-none absolute end-[28%] top-72 h-28 w-28 rounded-full bg-[#d8b36a]/20 blur-[45px]" />
      <div className="relative mx-auto grid max-w-[1440px] items-center gap-14 px-5 pb-20 sm:px-8 lg:grid-cols-[1.06fr_.94fr] lg:px-12 lg:pb-28">
        <div className="reveal max-w-3xl">
          <div className="mb-7 inline-flex items-center gap-3 rounded-full border border-[#d8b36a]/25 bg-[#d8b36a]/8 px-4 py-2 text-xs font-semibold tracking-wide text-[#edce8a]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#d8b36a]" />{t("شريكك لبناء ما بعد الممكن", "Your partner for what comes next")}</div>
          <h1 className="font-display text-[clamp(3.5rem,10vw,8.5rem)] font-semibold leading-[.94] tracking-[-.08em] text-[#f8f3eb]">{t("من الفكرة", "From idea")}<br /><span className="bg-gradient-to-l from-[#fff0bd] via-[#d8b36a] to-[#927138] bg-clip-text text-transparent">{t("إلى الأثر", "to impact")}</span></h1>
          <p className="mt-8 max-w-xl text-lg leading-9 text-[#b7aa9b] sm:text-xl">{t("نصمم ونبني منتجات رقمية، منصات، أنظمة ذكاء اصطناعي وأتمتة تخلق أثراً يتجاوز الإطلاق.", "We design and build digital products, platforms, AI systems, and automation that create impact beyond launch.")}</p>
          <div className="mt-9 flex flex-wrap gap-3"><Link href="/start-project" className="btn-primary">{t("ابدأ مشروعك", "Start your project")}<ArrowUpLeft size={17} /></Link><Link href="/services" className="btn-ghost">{t("اكتشف خدماتنا", "Explore services")}<ArrowLeft size={17} /></Link></div>
          <div className="mt-12 flex flex-wrap items-center gap-6 text-sm text-[#887d70]"><span className="flex items-center gap-2"><ShieldCheck size={16} className="text-[#d8b36a]" />{t("بنية موثوقة", "Reliable by design")}</span><span className="flex items-center gap-2"><Zap size={16} className="text-[#d8b36a]" />{t("تنفيذ رشيق", "Lean execution")}</span><span className="flex items-center gap-2"><CircleDot size={16} className="text-[#d8b36a]" />{t("شراكة طويلة", "Built to last")}</span></div>
        </div>
        <div className="relative hidden min-h-[480px] items-center justify-center lg:flex"><div className="float relative grid h-80 w-80 place-items-center rounded-[38%] border border-[#d8b36a]/35 bg-gradient-to-br from-[#d8b36a]/16 via-[#13110e] to-[#0b0a08] shadow-[0_0_120px_rgba(216,179,106,.14)] before:absolute before:inset-7 before:rounded-[34%] before:border before:border-[#d8b36a]/20 after:absolute after:-inset-10 after:rounded-full after:border after:border-[#d8b36a]/10"><div className="relative z-10 text-center"><div className="font-display text-8xl font-semibold tracking-[-.12em] text-[#edce8a]">أثر</div><div className="mt-2 text-xs uppercase tracking-[.4em] text-[#9b8866]">ATHR / 01</div></div></div><div className="absolute end-3 top-16 glass-gold rounded-2xl px-4 py-3 text-xs text-[#dbc391]"><span className="mb-1 block text-[10px] text-[#9a8663]">SYSTEM</span><span className="font-display">BUILD / SCALE</span></div><div className="absolute bottom-20 start-2 glass rounded-2xl px-4 py-3 text-xs text-[#b9ac9d]"><span className="mb-1 block text-[10px] text-[#9a8663]">STATUS</span><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-400" />{t("جاهز للأثر", "Ready for impact")}</span></div></div>
      </div>
      <div className="relative mx-auto grid max-w-[1440px] grid-cols-2 border-t border-white/8 px-5 sm:grid-cols-4 sm:px-8 lg:px-12">{[[stats.statProjects || "24", t("مشروعاً أطلقناه", "projects launched")], [stats.statClients || "18", t("شريكاً يثق بنا", "trusted partners")], [stats.statServices || "9", t("مجالات خبرة", "areas of craft")], [stats.statExperience || "7", t("سنوات من البناء", "years building")]].map(([value, label]) => <div key={label} className="border-s border-white/8 px-4 py-6 first:border-s-0 sm:px-7"><div className="font-display text-3xl text-[#edce8a]">{value}<span className="text-xl">{label === t("سنوات من البناء", "years building") ? "+" : ""}</span></div><div className="mt-1 text-xs text-[#83796c]">{label}</div></div>)}</div>
    </section>

    <section className="mx-auto max-w-[1440px] px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="grid gap-14 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><SectionHeading eyebrow={t("ما نبنيه", "What we build")} title={t("من التعقيد إلى الوضوح.", "From complexity to clarity.")} body={t("المنتجات الجيدة لا تبدأ بالتقنية. تبدأ بفهم عميق للمشكلة، ثم تتحول إلى تجربة تنمو مع الناس الذين يستخدمونها.", "Great products don't start with technology. They start with a deep understanding of the problem, then become experiences that grow with the people who use them.")} /><div className="grid gap-3 sm:grid-cols-2">{(data?.services ?? []).slice(0, 4).map((service, index) => { const Icon = iconMap[service.icon] ?? Layers3; return <Link href={`/services/${service.slug}`} key={service.id} className={`group glass rounded-3xl p-6 transition duration-300 hover:-translate-y-1 hover:border-[#d8b36a]/35 ${index === 0 ? "sm:translate-y-8" : ""}`}><div className="mb-8 flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl border border-[#d8b36a]/25 bg-[#d8b36a]/8 text-[#edce8a]"><Icon size={21} /></span><ArrowUpLeft size={18} className="text-[#726657] transition group-hover:-translate-y-1 group-hover:text-[#edce8a]" /></div><h3 className="text-lg font-semibold">{isArabic ? service.nameAr : service.nameEn}</h3><p className="mt-3 text-sm leading-7 text-[#978c7e]">{isArabic ? service.descriptionAr : service.descriptionEn}</p><div className="mt-5 flex flex-wrap gap-2">{service.technologies.slice(0, 3).map(tech => <span key={tech} className="rounded-full bg-white/5 px-2.5 py-1 text-[10px] text-[#8e8273]">{tech}</span>)}</div></Link>})}</div></div></section>

    <section className="border-y border-white/6 bg-[#0e0d0a] py-24 sm:py-32"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading eyebrow={t("أعمال تتحدث", "Selected work")} title={t("أثر قابل للقياس.", "Impact you can measure.")} body={t("لا نطارد المظهر وحده. نصمم أنظمة تجعل النتائج أوضح، أسرع، وأكثر قابلية للنمو.", "We don't chase surface-level polish. We design systems that make outcomes clearer, faster, and more scalable.")} /><Link href="/case-studies" className="btn-ghost shrink-0">{t("شاهد كل القصص", "View all stories")}<ArrowLeft size={17} /></Link></div><div className="mt-14 grid gap-5 lg:grid-cols-2">{(data?.caseStudies ?? []).slice(0, 2).map((item, index) => <Link href={`/case-studies/${item.slug}`} key={item.id} className={`group relative overflow-hidden rounded-[2rem] border border-white/8 bg-[#17130f] p-7 sm:p-10 ${index === 1 ? "lg:translate-y-12" : ""}`}><div className="absolute -end-14 -top-20 h-64 w-64 rounded-full bg-[#d8b36a]/10 blur-[70px] transition group-hover:bg-[#d8b36a]/18" /><div className="relative"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[.18em] text-[#d8b36a]">{item.category}</span><ArrowUpLeft size={20} className="text-[#75695b] transition group-hover:-translate-y-1 group-hover:text-[#edce8a]" /></div><h3 className="mt-16 max-w-md font-display text-3xl font-semibold leading-tight text-[#f8f3eb] sm:text-4xl">{isArabic ? item.titleAr : item.titleEn}</h3><p className="mt-5 max-w-lg leading-8 text-[#a29688]">{isArabic ? item.descriptionAr : item.descriptionEn}</p><div className="mt-9 grid grid-cols-3 gap-3 border-t border-white/10 pt-6">{item.results.slice(0, 3).map(result => <div key={result} className="text-sm font-medium text-[#edce8a]">{result}</div>)}</div></div></Link>)}</div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><SectionHeading eyebrow={t("كيف نعمل", "How we work")} title={t("عملية واضحة. أثر متراكم.", "Clear process. Compounding impact.")} body={t("كل قرار موثق، وكل مرحلة لها مخرج واضح — حتى تعرف دائماً أين نحن وإلى أين نتجه.", "Every decision is documented and every phase has a clear output — so you always know where we are and where we're going.")} /><Link href="/about" className="btn-ghost mt-8">{t("تعرف علينا أكثر", "Meet ATHR")}<ArrowLeft size={17} /></Link></div><div className="space-y-3">{process.map(([number, ar, en]) => <div key={number} className="group flex items-center gap-5 border-b border-white/8 py-5 transition hover:border-[#d8b36a]/35"><span className="font-display text-xs tracking-[.18em] text-[#6f6458]">{number}</span><span className="flex-1 text-xl font-medium text-[#cfc5b8] transition group-hover:text-[#edce8a]">{t(ar, en)}</span><ArrowUpLeft size={18} className="text-[#6f6458] transition group-hover:-translate-y-1 group-hover:text-[#edce8a]" /></div>)}</div></div></section>

    <section className="bg-[#0e0d0b] py-24 sm:py-32"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><SectionHeading eyebrow={t("صوت الشراكة", "In their words")} title={t("الشراكة التي تشعر بها.", "A partnership you can feel.")} body={t("نقيس نجاحنا بما يتغير في عملك، لا بما نضيفه إلى قائمة مشاريعنا.", "We measure success by what changes in your business, not by what we add to our project list.")} /><div className="space-y-4">{(data?.testimonials ?? []).map(item => <div key={item.id} className="glass rounded-3xl p-7"><Quote size={24} className="text-[#d8b36a]" /><p className="mt-5 text-lg leading-9 text-[#ddd3c6]">“{isArabic ? item.messageAr : item.messageEn}”</p><div className="mt-7 flex items-center justify-between border-t border-white/8 pt-5"><div><div className="font-semibold text-[#f7f2e9]">{item.clientName}</div><div className="mt-1 text-xs text-[#8e8274]">{item.position} · {item.company}</div></div><div className="text-[#d8b36a]">{"★".repeat(item.rating)}</div></div></div>)}</div></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading eyebrow={t("الأسئلة الشائعة", "FAQ")} title={t("أسئلة قبل البداية؟", "Questions before we begin?")} /><Link href="/faq" className="btn-ghost shrink-0">{t("كل الأسئلة", "All questions")}<ArrowLeft size={17} /></Link></div><div className="mt-12 max-w-4xl">{(data?.faqs ?? []).slice(0, 4).map(item => <div key={item.id} className="border-b border-white/8"><button type="button" className="flex w-full items-center justify-between gap-6 py-6 text-start text-lg font-medium text-[#e7dfd4]" onClick={() => setOpenFaq(openFaq === item.id ? null : item.id)}>{isArabic ? item.questionAr : item.questionEn}<ChevronDown size={19} className={`shrink-0 text-[#d8b36a] transition ${openFaq === item.id ? "rotate-180" : ""}`} /></button>{openFaq === item.id && <p className="pb-6 leading-8 text-[#9b9083]">{isArabic ? item.answerAr : item.answerEn}</p>}</div>)}</div></section>

    <section className="px-5 pb-24 sm:px-8 lg:px-12"><div className="relative mx-auto max-w-[1440px] overflow-hidden rounded-[2rem] border border-[#d8b36a]/25 bg-gradient-to-br from-[#221b10] to-[#12100d] px-7 py-14 sm:px-14 sm:py-20"><div className="absolute -end-16 -top-28 h-80 w-80 rounded-full bg-[#d8b36a]/12 blur-[85px]" /><div className="relative flex flex-col justify-between gap-10 md:flex-row md:items-end"><div><div className="mb-5 flex items-center gap-3 text-xs font-semibold uppercase tracking-[.2em] text-[#d8b36a]"><span className="h-px w-8 bg-[#d8b36a]" />{t("الخطوة التالية", "The next step")}</div><h2 className="max-w-2xl font-display text-4xl font-semibold leading-tight text-[#f8f3eb] sm:text-6xl">{t("جاهز تحول فكرتك إلى أثر؟", "Ready to turn your idea into impact?")}</h2></div><Link href="/start-project" className="btn-primary shrink-0">{t("ابدأ مشروعك", "Start a project")}<ArrowUpLeft size={18} /></Link></div></div></section>
    {isLoading && <div className="sr-only">Loading</div>}{error && <div className="sr-only">Unable to load public content</div>}
  </PublicShell>;
}
